workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        CM_KEYCHAIN_PATH: Encrypted(...)  # Your encrypted keychain file
        CM_CERTIFICATE: Encrypted(...)    # Your encrypted certificate
        CM_CERTIFICATE_PASSWORD: Encrypted(...)  # Your certificate password
        CM_PROVISIONING_PROFILE: Encrypted(...)  # Your provisioning profile
      xcode: latest
    triggering:
      events:
        - push
        - pull_request
    scripts:
      - name: Install dependencies
        script: |
          brew install cocoapods
          pod install
      - name: Set up keychain
        script: |
          cm_keychain -k $CM_KEYCHAIN_PATH -c $CM_CERTIFICATE -p $CM_CERTIFICATE_PASSWORD
      - name: Build IPA
        script: |
          xcodebuild -workspace MyApp.xcworkspace -scheme MyApp -sdk iphoneos -configuration AppStoreDistribution archive -archivePath $CM_BUILD_DIR/MyApp.xcarchive
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/MyApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - user@example.com
